server:
  port: 8080

demo:
  kafka:
    user-mutation:
      topic:
        name: demo.user-mutation.v1
spring:
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:8085
    producer:
      properties:
        auto.register.schemas: true
        security.protocol: PLAINTEXT
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.github.thake.kafka.avro4k.serializer.KafkaAvro4kSerializer
    consumer:
      properties:
        security.protocol: PLAINTEXT
        record.packages: "com.example.demo.model"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.github.thake.kafka.avro4k.serializer.KafkaAvro4kDeserializer
